name: Build and push container

on: [push]

jobs:
  build:
    env:
      IMAGE_NAME: quay.io/fbenoit/runtime-plugin-java

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Docker build
      run: |
        echo "Building image ${IMAGE_NAME}"
        docker build -t ${IMAGE_NAME} .

    - name: Docker publish
      run: |
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" quay.io
        GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        if [[ "$GIT_BRANCH" == "master" ]]; then
          GIT_TAG="latest"
        else
          GIT_TAG=${GIT_BRANCH}
        fi
        # Publish with tag name
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${GIT_TAG}"
        docker push "${IMAGE_NAME}:${GIT_TAG}
        # and with specific sha-1
        SHORT_SHA1=$(git rev-parse --short HEAD)
        docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${SHORT_SHA1}"
        docker push "${IMAGE_NAME}:${SHORT_SHA1}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
